### ISSUE TITLE
[Node Version] Node Version 20 Support 

### ISSUE THREAD

**Issue by SylvainJGA** [chili-publish/studio-sdk#338]
Hello,

Is it possible to support a newer version of node?

error @chili-publish/studio-sdk@0.142.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <19.0.0".

Regards,

Sylvain Jochemczak

**Comment by brapoprod** [comment]
.Hi Sylvain,

Thanks for flagging this dependency issue.

I have created a PR to fix it, once it is accepted by our review process it will be merged.

**Comment by brapoprod** [comment]
Fixed in #341 if there is anything else, please let us know.
