### ISSUE TITLE
[Feature Request] Frame - getIsVisible

### ISSUE THREAD

**Issue by SylvainJGA** [chili-publish/studio-sdk#348]
Hello,

I need to know if frame is visible or not

Would it be possible to add a method getIsVisible on frame or add props on frame object ?

I tried to see if we had this property when we get a frame with frame.getByName but I only see blendMode, constrainProportions, id, src, name and type

Regards,

Sylvain.

**Comment by Matthiee** [comment]
Hi @SylvainJGA,

Make sure you are using the following SDK version https://github.com/chili-publish/studio-sdk/releases/tag/0.148.0

In short, you can use the following SDK method to get the visibility state of the frame. 

```typescript
await SDK.frame.getLayoutProperties('frameId');
```

One of the properties will be `isVisible`. The `value` is the actual visibility state on this layout, `isOverride` indicates if the value is overridden on this layout or [inherited](https://docs.chiligrafx.com/GraFx-Studio/concepts/layouts/#inheritance).

The reason why they are split up is the following: 
The `SDK.frame.getByName` will return the content of the frame. The content of the frame remains the same for each layout. The properties of the frame can change from layout to layout. 

If there is anything else, please let us know.

**Comment by SylvainJGA** [comment]
Hi @Matthiee ,

It's working fine, thank for your help.
